<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Vehicle;
use App\Models\MaintenanceLog;
use App\Models\User;
use Carbon\Carbon;

class VehicleSeeder extends Seeder
{
    public function run(): void
    {
        // Comprehensive vehicle data with ALL fields needed for fleet status
        $vehicles = [
            // VANS
            [
                'vehicle_number' => 'LG-001-AA',
                'vehicle_name' => 'Delivery Van 1',
                'vehicle_type' => 'van',
                'make' => 'Toyota',
                'model' => 'Hiace',
                'year' => 2022,
                'color' => 'White',
                'capacity_weight' => 1000.00,
                'capacity_volume' => 15.00,
                'vin' => '1HGCM82633A123456',
                'license_plate' => 'VAN-001-LG-001-AA',
                'assigned_driver_id' => 4,
                'warehouse_id' => 1,
                'hub_id' => 1,
                'status' => 'active',
                'registration_date' => '2022-01-15',
                'registration_expiry' => '2025-01-15',
                'insurance_expiry' => '2025-06-30',
                'insurance_company' => 'AXA Mansard',
                'insurance_policy_number' => 'AXA-2022-001',
                'fuel_type' => 'diesel',
                // Fleet Status specific fields
                'current_location' => 'Lagos, Nigeria',
                'current_latitude' => 6.5244,
                'current_longitude' => 3.3792,
                'current_fuel_level' => 75,
                'mileage' => 45000,
                'fuel_efficiency_mpg' => 8.2,
                'fuel_capacity' => 60.00,
                'last_service_date' => Carbon::now()->subMonths(2),
                'next_service_date' => Carbon::now()->addMonth(),
                'total_trips' => 150,
                'total_distance' => 45000,
                'avg_speed' => 45.5,
                'utilization_percentage' => 85.5,
            ],
            [
                'vehicle_number' => 'LG-004-DD',
                'vehicle_name' => 'Delivery Van 2',
                'vehicle_type' => 'van',
                'make' => 'Mercedes-Benz',
                'model' => 'Sprinter',
                'year' => 2023,
                'color' => 'White',
                'capacity_weight' => 1200.00,
                'capacity_volume' => 18.00,
                'vin' => '2HGCM82633A789012',
                'license_plate' => 'VAN-002-LG-004-DD',
                'assigned_driver_id' => null,
                'warehouse_id' => 1,
                'hub_id' => 1,
                'status' => 'inactive',
                'registration_date' => '2023-01-15',
                'registration_expiry' => '2026-01-15',
                'insurance_expiry' => '2025-12-31',
                'insurance_company' => 'AXA Mansard',
                'insurance_policy_number' => 'AXA-2023-004',
                'fuel_type' => 'diesel',
                'current_location' => 'Lagos, Nigeria',
                'current_latitude' => 6.4541,
                'current_longitude' => 3.3947,
                'current_fuel_level' => 90,
                'mileage' => 12000,
                'fuel_efficiency_mpg' => 8.5,
                'fuel_capacity' => 70.00,
                'last_service_date' => Carbon::now()->subMonth(),
                'next_service_date' => Carbon::now()->addMonths(2),
                'total_trips' => 50,
                'total_distance' => 12000,
                'avg_speed' => 48.0,
                'utilization_percentage' => 0,
            ],
            
            // TRUCKS
            [
                'vehicle_number' => 'LG-002-BB',
                'vehicle_name' => 'Delivery Truck 1',
                'vehicle_type' => 'truck',
                'make' => 'Isuzu',
                'model' => 'NPR',
                'year' => 2021,
                'color' => 'Blue',
                'capacity_weight' => 3000.00,
                'capacity_volume' => 40.00,
                'vin' => '3HGCM82633A345678',
                'license_plate' => 'TRK-001-LG-002-BB',
                'assigned_driver_id' => 5,
                'warehouse_id' => 1,
                'hub_id' => 1,
                'status' => 'active',
                'registration_date' => '2021-05-20',
                'registration_expiry' => '2024-05-20',
                'insurance_expiry' => '2024-12-31',
                'insurance_company' => 'Leadway Assurance',
                'insurance_policy_number' => 'LEAD-2021-002',
                'fuel_type' => 'diesel',
                'current_location' => 'Abuja, Nigeria',
                'current_latitude' => 9.0765,
                'current_longitude' => 7.3986,
                'current_fuel_level' => 55,
                'mileage' => 78000,
                'fuel_efficiency_mpg' => 7.5,
                'fuel_capacity' => 100.00,
                'last_service_date' => Carbon::now()->subMonths(3),
                'next_service_date' => Carbon::now()->addWeeks(2),
                'total_trips' => 320,
                'total_distance' => 78000,
                'avg_speed' => 52.0,
                'utilization_percentage' => 92.0,
            ],
            [
                'vehicle_number' => 'TRK-002',
                'vehicle_name' => 'Delivery Truck 2',
                'vehicle_type' => 'truck',
                'make' => 'Freightliner',
                'model' => 'Cascadia',
                'year' => 2022,
                'color' => 'White',
                'capacity_weight' => 5000.00,
                'capacity_volume' => 60.00,
                'vin' => '4HGCM82633A901234',
                'license_plate' => 'LG-005-EE',
                'assigned_driver_id' => null,
                'warehouse_id' => 2,
                'hub_id' => 2,
                'status' => 'maintenance',
                'registration_date' => '2022-03-10',
                'registration_expiry' => '2025-03-10',
                'insurance_expiry' => '2025-09-30',
                'insurance_company' => 'Custodian Insurance',
                'insurance_policy_number' => 'CUST-2022-005',
                'fuel_type' => 'diesel',
                'current_location' => 'Port Harcourt, Nigeria',
                'current_latitude' => 4.8156,
                'current_longitude' => 7.0498,
                'current_fuel_level' => 40,
                'mileage' => 95000,
                'fuel_efficiency_mpg' => 7.2,
                'fuel_capacity' => 120.00,
                'last_service_date' => Carbon::now()->subDays(5),
                'next_service_date' => Carbon::now()->addMonths(3),
                'total_trips' => 450,
                'total_distance' => 95000,
                'avg_speed' => 50.0,
                'utilization_percentage' => 0,
                'alert_type' => 'maintenance_due',
                'alert_message' => 'Scheduled maintenance in progress',
            ],
            
            // BIKES
            [
                'vehicle_number' => 'BIKE-001',
                'vehicle_name' => 'Delivery Bike 1',
                'vehicle_type' => 'bike',
                'make' => 'Honda',
                'model' => 'CG 125',
                'year' => 2023,
                'color' => 'Red',
                'capacity_weight' => 30.00,
                'capacity_volume' => 0.50,
                'vin' => '5HGCM82633A567890',
                'license_plate' => 'LG-003-CC',
                'assigned_driver_id' => 6,
                'warehouse_id' => 2,
                'hub_id' => 2,
                'status' => 'active',
                'registration_date' => '2023-03-10',
                'registration_expiry' => '2026-03-10',
                'insurance_expiry' => '2025-03-10',
                'insurance_company' => 'Custodian Insurance',
                'insurance_policy_number' => 'CUST-2023-003',
                'fuel_type' => 'petrol',
                'current_location' => 'Kano, Nigeria',
                'current_latitude' => 12.0022,
                'current_longitude' => 8.5919,
                'current_fuel_level' => 80,
                'mileage' => 15000,
                'fuel_efficiency_mpg' => 45.0,
                'fuel_capacity' => 12.00,
                'last_service_date' => Carbon::now()->subWeeks(3),
                'next_service_date' => Carbon::now()->addMonths(2),
                'total_trips' => 280,
                'total_distance' => 15000,
                'avg_speed' => 35.0,
                'utilization_percentage' => 78.5,
            ],
            [
                'vehicle_number' => 'BIKE-002',
                'vehicle_name' => 'Delivery Bike 2',
                'vehicle_type' => 'bike',
                'make' => 'Yamaha',
                'model' => 'YBR 125',
                'year' => 2023,
                'color' => 'Blue',
                'capacity_weight' => 35.00,
                'capacity_volume' => 0.60,
                'vin' => '6HGCM82633A123789',
                'license_plate' => 'LG-006-FF',
                'assigned_driver_id' => null,
                'warehouse_id' => 1,
                'hub_id' => 1,
                'status' => 'repair',
                'registration_date' => '2023-06-15',
                'registration_expiry' => '2026-06-15',
                'insurance_expiry' => '2025-06-15',
                'insurance_company' => 'AXA Mansard',
                'insurance_policy_number' => 'AXA-2023-006',
                'fuel_type' => 'petrol',
                'current_location' => 'Lagos, Nigeria',
                'current_latitude' => 6.5244,
                'current_longitude' => 3.3792,
                'current_fuel_level' => 20,
                'mileage' => 8500,
                'fuel_efficiency_mpg' => 42.0,
                'fuel_capacity' => 13.00,
                'last_service_date' => Carbon::now()->subMonths(4),
                'next_service_date' => Carbon::now()->subWeeks(2),
                'total_trips' => 120,
                'total_distance' => 8500,
                'avg_speed' => 32.0,
                'utilization_percentage' => 0,
                'alert_type' => 'breakdown',
                'alert_message' => 'Engine failure - awaiting parts',
            ],
            
            // CARS
            [
                'vehicle_number' => 'CAR-001',
                'vehicle_name' => 'Executive Car 1',
                'vehicle_type' => 'car',
                'make' => 'Toyota',
                'model' => 'Camry',
                'year' => 2023,
                'color' => 'Silver',
                'capacity_weight' => 400.00,
                'capacity_volume' => 2.00,
                'vin' => '7HGCM82633A456123',
                'license_plate' => 'LG-007-GG',
                'assigned_driver_id' => null,
                'warehouse_id' => 1,
                'hub_id' => 1,
                'status' => 'active',
                'registration_date' => '2023-08-01',
                'registration_expiry' => '2026-08-01',
                'insurance_expiry' => '2025-08-01',
                'insurance_company' => 'Leadway Assurance',
                'insurance_policy_number' => 'LEAD-2023-007',
                'fuel_type' => 'petrol',
                'current_location' => 'Ibadan, Nigeria',
                'current_latitude' => 7.3775,
                'current_longitude' => 3.9470,
                'current_fuel_level' => 65,
                'mileage' => 5000,
                'fuel_efficiency_mpg' => 28.0,
                'fuel_capacity' => 50.00,
                'last_service_date' => Carbon::now()->subMonth(),
                'next_service_date' => Carbon::now()->addMonths(5),
                'total_trips' => 45,
                'total_distance' => 5000,
                'avg_speed' => 60.0,
                'utilization_percentage' => 45.0,
            ],
        ];

        foreach ($vehicles as $vehicleData) {
            $vehicle = Vehicle::create($vehicleData);
            
            // Create maintenance logs for each vehicle
            $this->createMaintenanceLogs($vehicle);
        }
    }

    private function createMaintenanceLogs($vehicle)
    {
        $maintenanceTypes = ['scheduled', 'inspection', 'service', 'breakdown', 'repair'];
        
        // Past maintenance (last 6 months)
        for ($i = 0; $i < 3; $i++) {
            $date = Carbon::now()->subMonths($i * 2);
            $isPreventive = rand(0, 10) > 3;
            
            MaintenanceLog::create([
                'log_number' => 'MAINT-' . $vehicle->id . '-' . str_pad($i + 1, 4, '0', STR_PAD_LEFT),
                'vehicle_id' => $vehicle->id,
                'maintenance_type' => $isPreventive ? $maintenanceTypes[rand(0, 2)] : $maintenanceTypes[rand(3, 4)],
                'maintenance_date' => $date,
                'next_maintenance_date' => $date->copy()->addMonths(3),
                'cost' => $isPreventive ? rand(800, 2500) : rand(3000, 8000),
                'vendor_name' => ['AAA Auto Service', 'Quick Fix Garage', 'Premium Motors', 'City Auto Repair'][rand(0, 3)],
                'description' => $isPreventive 
                    ? 'Regular maintenance and inspection' 
                    : 'Emergency repair and parts replacement',
                'priority' => $isPreventive ? 'medium' : 'high',
                'category' => ['Engine', 'Transmission', 'Brakes', 'Electrical', 'Tires'][rand(0, 4)],
                'technician_name' => ['John Doe', 'Jane Smith', 'Mike Johnson', 'Sarah Williams'][rand(0, 3)],
                'mileage_at_maintenance' => max(0, $vehicle->mileage - (rand(5000, 15000) * $i)),
                'status' => 'completed',
            ]);
        }
        
        // Upcoming maintenance
        if ($vehicle->status !== 'repair') {
            MaintenanceLog::create([
                'log_number' => 'MAINT-' . $vehicle->id . '-NEXT',
                'vehicle_id' => $vehicle->id,
                'maintenance_type' => 'scheduled',
                'maintenance_date' => $vehicle->next_service_date,
                'cost' => rand(1200, 2000),
                'vendor_name' => 'AAA Auto Service',
                'description' => 'Scheduled maintenance service',
                'priority' => 'medium',
                'category' => 'General',
                'status' => 'scheduled',
            ]);
        }
    }
}