<?php

namespace Database\Seeders;

use App\Models\Warehouse;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class WarehouseSeeder extends Seeder
{
    public function run()
    {
        $this->command->info('Starting Warehouse Seeder...');
        
        // Disable foreign key checks
        DB::statement('SET FOREIGN_KEY_CHECKS=0;');
        
        try {
            // Clear existing warehouses
            $this->command->info('Clearing existing warehouses...');
            Warehouse::truncate();
            
            $warehousesData = $this->getWarehouseData();
            
            $this->command->info('Creating ' . count($warehousesData) . ' warehouses...');
            $successCount = 0;
            $errorCount = 0;

            foreach ($warehousesData as $index => $data) {
                try {
                    Warehouse::create($data);
                    $successCount++;
                    
                    if (($index + 1) % 5 == 0) {
                        $this->command->info("Created " . ($index + 1) . " warehouses...");
                    }
                    
                } catch (\Exception $e) {
                    $errorCount++;
                    $this->command->error("Failed to create warehouse {$data['name']}: " . $e->getMessage());
                }
            }

            DB::statement('SET FOREIGN_KEY_CHECKS=1;');
            
            $this->command->info("✅ Seeder completed!");
            $this->command->info("Successfully created: $successCount warehouses");
            if ($errorCount > 0) {
                $this->command->warn("Failed to create: $errorCount warehouses");
            }
            
        } catch (\Exception $e) {
            DB::statement('SET FOREIGN_KEY_CHECKS=1;');
            $this->command->error('Seeder failed: ' . $e->getMessage());
            $this->command->error('Trace: ' . $e->getTraceAsString());
        }
    }

    private function getWarehouseData()
    {
        return [
            // Lagos Warehouses
            [
                'warehouse_code' => 'WH-LAG-001',
                'name' => 'Lagos Main Warehouse',
                'type' => 'main',
                'address' => '45 Warehouse Road, Apapa',
                'city' => 'Lagos',
                'state' => 'Lagos',
                'country' => 'Nigeria',
                'postal_code' => '101245',
                'phone' => '+234-801-234-5001',
                'email' => 'lagos.main@warehouse.ng',
                'manager_name' => 'Adebayo Ogunlesi',
                'manager_phone' => '+234-802-345-6001',
                'latitude' => 6.4394,
                'longitude' => 3.3617,
                'storage_capacity' => 5000,
                'current_occupancy' => rand(2500, 4500),
                'area_sqm' => 3500.00,
                'loading_docks' => 12,
                'staff_count' => 45,
                'opening_time' => '06:00:00',
                'closing_time' => '22:00:00',
                'operating_days' => json_encode(['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday']),
                'status' => 'active',
                'is_pickup_point' => true,
                'is_delivery_point' => true,
                'accepts_cod' => true,
                'has_cold_storage' => true,
                'has_24h_security' => true,
                'monthly_rent' => 1500000.00,
                'utility_cost' => 250000.00,
                'total_shipments_processed' => rand(15000, 25000),
                'total_deliveries_completed' => rand(12000, 20000),
                'average_processing_time' => rand(2, 6) + (rand(0, 99) / 100),
                'utilization_percentage' => rand(60, 90) + (rand(0, 99) / 100),
                'license_number' => 'WHL-LAG-2023-001',
                'license_expiry' => Carbon::now()->addYears(2),
                'last_inspection_date' => Carbon::now()->subMonths(rand(1, 6)),
                'safety_rating' => 'A',
                'description' => 'Main distribution hub for Lagos and surrounding areas. Equipped with modern sorting equipment and cold storage facilities.',
                'special_instructions' => 'High-value items section on 2nd floor. Cold storage requires special access.',
                'created_at' => Carbon::now()->subMonths(rand(12, 36)),
                'updated_at' => now(),
            ],
            [
                'warehouse_code' => 'WH-LAG-002',
                'name' => 'Ikeja Regional Warehouse',
                'type' => 'regional',
                'address' => '23 Industrial Avenue, Ikeja',
                'city' => 'Lagos',
                'state' => 'Lagos',
                'country' => 'Nigeria',
                'postal_code' => '100271',
                'phone' => '+234-801-234-5002',
                'email' => 'ikeja@warehouse.ng',
                'manager_name' => 'Chioma Nwosu',
                'manager_phone' => '+234-802-345-6002',
                'latitude' => 6.5964,
                'longitude' => 3.3397,
                'storage_capacity' => 3000,
                'current_occupancy' => rand(1500, 2700),
                'area_sqm' => 2200.00,
                'loading_docks' => 8,
                'staff_count' => 28,
                'opening_time' => '07:00:00',
                'closing_time' => '20:00:00',
                'operating_days' => json_encode(['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday']),
                'status' => 'active',
                'is_pickup_point' => true,
                'is_delivery_point' => true,
                'accepts_cod' => true,
                'has_cold_storage' => false,
                'has_24h_security' => true,
                'monthly_rent' => 900000.00,
                'utility_cost' => 150000.00,
                'total_shipments_processed' => rand(8000, 15000),
                'total_deliveries_completed' => rand(6000, 12000),
                'average_processing_time' => rand(3, 7) + (rand(0, 99) / 100),
                'utilization_percentage' => rand(55, 85) + (rand(0, 99) / 100),
                'license_number' => 'WHL-LAG-2023-002',
                'license_expiry' => Carbon::now()->addYears(2),
                'last_inspection_date' => Carbon::now()->subMonths(rand(1, 6)),
                'safety_rating' => 'A',
                'description' => 'Regional warehouse serving Ikeja and surrounding districts.',
                'created_at' => Carbon::now()->subMonths(rand(12, 36)),
                'updated_at' => now(),
            ],
            [
                'warehouse_code' => 'WH-LAG-003',
                'name' => 'Victoria Island Distribution Center',
                'type' => 'distribution',
                'address' => '12 Akin Adesola Street, Victoria Island',
                'city' => 'Lagos',
                'state' => 'Lagos',
                'country' => 'Nigeria',
                'postal_code' => '106104',
                'phone' => '+234-801-234-5003',
                'email' => 'vi@warehouse.ng',
                'manager_name' => 'Ibrahim Yusuf',
                'manager_phone' => '+234-802-345-6003',
                'latitude' => 6.4281,
                'longitude' => 3.4219,
                'storage_capacity' => 1500,
                'current_occupancy' => rand(800, 1400),
                'area_sqm' => 1200.00,
                'loading_docks' => 5,
                'staff_count' => 18,
                'opening_time' => '08:00:00',
                'closing_time' => '18:00:00',
                'operating_days' => json_encode(['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday']),
                'status' => 'active',
                'is_pickup_point' => true,
                'is_delivery_point' => true,
                'accepts_cod' => true,
                'has_cold_storage' => false,
                'has_24h_security' => true,
                'monthly_rent' => 1200000.00,
                'utility_cost' => 180000.00,
                'total_shipments_processed' => rand(5000, 10000),
                'total_deliveries_completed' => rand(4000, 8000),
                'average_processing_time' => rand(2, 5) + (rand(0, 99) / 100),
                'utilization_percentage' => rand(50, 80) + (rand(0, 99) / 100),
                'license_number' => 'WHL-LAG-2024-003',
                'license_expiry' => Carbon::now()->addYears(1),
                'last_inspection_date' => Carbon::now()->subMonths(rand(1, 4)),
                'safety_rating' => 'B',
                'description' => 'Express delivery hub for Victoria Island business district.',
                'created_at' => Carbon::now()->subMonths(rand(6, 24)),
                'updated_at' => now(),
            ],

            // Abuja Warehouses
            [
                'warehouse_code' => 'WH-ABJ-001',
                'name' => 'Abuja Central Warehouse',
                'type' => 'main',
                'address' => '78 Airport Road, Lugbe',
                'city' => 'Abuja',
                'state' => 'Federal Capital Territory',
                'country' => 'Nigeria',
                'postal_code' => '900108',
                'phone' => '+234-803-234-5004',
                'email' => 'abuja.main@warehouse.ng',
                'manager_name' => 'Fatima Abdullahi',
                'manager_phone' => '+234-804-345-6004',
                'latitude' => 8.9806,
                'longitude' => 7.1858,
                'storage_capacity' => 4000,
                'current_occupancy' => rand(2000, 3600),
                'area_sqm' => 2800.00,
                'loading_docks' => 10,
                'staff_count' => 35,
                'opening_time' => '06:00:00',
                'closing_time' => '21:00:00',
                'operating_days' => json_encode(['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday']),
                'status' => 'active',
                'is_pickup_point' => true,
                'is_delivery_point' => true,
                'accepts_cod' => true,
                'has_cold_storage' => true,
                'has_24h_security' => true,
                'monthly_rent' => 1300000.00,
                'utility_cost' => 220000.00,
                'total_shipments_processed' => rand(12000, 20000),
                'total_deliveries_completed' => rand(10000, 18000),
                'average_processing_time' => rand(3, 6) + (rand(0, 99) / 100),
                'utilization_percentage' => rand(65, 88) + (rand(0, 99) / 100),
                'license_number' => 'WHL-ABJ-2023-001',
                'license_expiry' => Carbon::now()->addYears(2),
                'last_inspection_date' => Carbon::now()->subMonths(rand(1, 5)),
                'safety_rating' => 'A',
                'description' => 'Primary logistics hub for Federal Capital Territory and North Central region.',
                'special_instructions' => 'Government and diplomatic packages require special clearance.',
                'created_at' => Carbon::now()->subMonths(rand(12, 36)),
                'updated_at' => now(),
            ],
            [
                'warehouse_code' => 'WH-ABJ-002',
                'name' => 'Wuse Sortation Center',
                'type' => 'sortation',
                'address' => '15 Adetokunbo Ademola Crescent, Wuse II',
                'city' => 'Abuja',
                'state' => 'Federal Capital Territory',
                'country' => 'Nigeria',
                'postal_code' => '900288',
                'phone' => '+234-803-234-5005',
                'email' => 'wuse@warehouse.ng',
                'manager_name' => 'Emmanuel Okafor',
                'manager_phone' => '+234-804-345-6005',
                'latitude' => 9.0579,
                'longitude' => 7.4951,
                'storage_capacity' => 2000,
                'current_occupancy' => rand(1000, 1800),
                'area_sqm' => 1500.00,
                'loading_docks' => 6,
                'staff_count' => 22,
                'opening_time' => '07:00:00',
                'closing_time' => '19:00:00',
                'operating_days' => json_encode(['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday']),
                'status' => 'active',
                'is_pickup_point' => true,
                'is_delivery_point' => true,
                'accepts_cod' => true,
                'has_cold_storage' => false,
                'has_24h_security' => true,
                'monthly_rent' => 800000.00,
                'utility_cost' => 130000.00,
                'total_shipments_processed' => rand(6000, 12000),
                'total_deliveries_completed' => rand(5000, 10000),
                'average_processing_time' => rand(2, 4) + (rand(0, 99) / 100),
                'utilization_percentage' => rand(55, 82) + (rand(0, 99) / 100),
                'license_number' => 'WHL-ABJ-2024-002',
                'license_expiry' => Carbon::now()->addYears(1),
                'last_inspection_date' => Carbon::now()->subMonths(rand(1, 4)),
                'safety_rating' => 'B',
                'description' => 'Rapid sortation facility for express deliveries in Abuja city center.',
                'created_at' => Carbon::now()->subMonths(rand(6, 24)),
                'updated_at' => now(),
            ],

            // Port Harcourt Warehouse
            [
                'warehouse_code' => 'WH-PHC-001',
                'name' => 'Port Harcourt Regional Hub',
                'type' => 'regional',
                'address' => '34 Trans Amadi Industrial Layout',
                'city' => 'Port Harcourt',
                'state' => 'Rivers',
                'country' => 'Nigeria',
                'postal_code' => '500272',
                'phone' => '+234-805-234-5006',
                'email' => 'portharcourt@warehouse.ng',
                'manager_name' => 'Blessing Amadi',
                'manager_phone' => '+234-806-345-6006',
                'latitude' => 4.8156,
                'longitude' => 7.0498,
                'storage_capacity' => 3500,
                'current_occupancy' => rand(1800, 3200),
                'area_sqm' => 2400.00,
                'loading_docks' => 9,
                'staff_count' => 30,
                'opening_time' => '06:30:00',
                'closing_time' => '20:30:00',
                'operating_days' => json_encode(['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday']),
                'status' => 'active',
                'is_pickup_point' => true,
                'is_delivery_point' => true,
                'accepts_cod' => true,
                'has_cold_storage' => true,
                'has_24h_security' => true,
                'monthly_rent' => 950000.00,
                'utility_cost' => 170000.00,
                'total_shipments_processed' => rand(10000, 18000),
                'total_deliveries_completed' => rand(8000, 15000),
                'average_processing_time' => rand(3, 7) + (rand(0, 99) / 100),
                'utilization_percentage' => rand(60, 87) + (rand(0, 99) / 100),
                'license_number' => 'WHL-PHC-2023-001',
                'license_expiry' => Carbon::now()->addYears(2),
                'last_inspection_date' => Carbon::now()->subMonths(rand(1, 6)),
                'safety_rating' => 'A',
                'description' => 'Main logistics facility for South-South region with oil & gas industry focus.',
                'special_instructions' => 'Industrial equipment handling available. Hazmat certified.',
                'created_at' => Carbon::now()->subMonths(rand(12, 36)),
                'updated_at' => now(),
            ],

            // Kano Warehouse
            [
                'warehouse_code' => 'WH-KAN-001',
                'name' => 'Kano Northern Hub',
                'type' => 'main',
                'address' => '56 Bompai Road, Nasarawa',
                'city' => 'Kano',
                'state' => 'Kano',
                'country' => 'Nigeria',
                'postal_code' => '700221',
                'phone' => '+234-807-234-5007',
                'email' => 'kano@warehouse.ng',
                'manager_name' => 'Musa Garba',
                'manager_phone' => '+234-808-345-6007',
                'latitude' => 12.0022,
                'longitude' => 8.5919,
                'storage_capacity' => 3800,
                'current_occupancy' => rand(1900, 3400),
                'area_sqm' => 2600.00,
                'loading_docks' => 10,
                'staff_count' => 32,
                'opening_time' => '06:00:00',
                'closing_time' => '21:00:00',
                'operating_days' => json_encode(['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday']),
                'status' => 'active',
                'is_pickup_point' => true,
                'is_delivery_point' => true,
                'accepts_cod' => true,
                'has_cold_storage' => true,
                'has_24h_security' => true,
                'monthly_rent' => 750000.00,
                'utility_cost' => 140000.00,
                'total_shipments_processed' => rand(11000, 19000),
                'total_deliveries_completed' => rand(9000, 16000),
                'average_processing_time' => rand(3, 7) + (rand(0, 99) / 100),
                'utilization_percentage' => rand(62, 86) + (rand(0, 99) / 100),
                'license_number' => 'WHL-KAN-2023-001',
                'license_expiry' => Carbon::now()->addYears(2),
                'last_inspection_date' => Carbon::now()->subMonths(rand(1, 5)),
                'safety_rating' => 'A',
                'description' => 'Strategic hub serving entire Northern Nigeria region.',
                'created_at' => Carbon::now()->subMonths(rand(12, 36)),
                'updated_at' => now(),
            ],

            // Ibadan Warehouse
            [
                'warehouse_code' => 'WH-IBD-001',
                'name' => 'Ibadan Distribution Center',
                'type' => 'distribution',
                'address' => '28 Challenge Road, Ibadan',
                'city' => 'Ibadan',
                'state' => 'Oyo',
                'country' => 'Nigeria',
                'postal_code' => '200284',
                'phone' => '+234-809-234-5008',
                'email' => 'ibadan@warehouse.ng',
                'manager_name' => 'Kehinde Ajayi',
                'manager_phone' => '+234-810-345-6008',
                'latitude' => 7.3775,
                'longitude' => 3.9470,
                'storage_capacity' => 2500,
                'current_occupancy' => rand(1200, 2300),
                'area_sqm' => 1800.00,
                'loading_docks' => 7,
                'staff_count' => 24,
                'opening_time' => '07:00:00',
                'closing_time' => '20:00:00',
                'operating_days' => json_encode(['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday']),
                'status' => 'active',
                'is_pickup_point' => true,
                'is_delivery_point' => true,
                'accepts_cod' => true,
                'has_cold_storage' => false,
                'has_24h_security' => true,
                'monthly_rent' => 650000.00,
                'utility_cost' => 120000.00,
                'total_shipments_processed' => rand(7000, 14000),
                'total_deliveries_completed' => rand(6000, 12000),
                'average_processing_time' => rand(3, 6) + (rand(0, 99) / 100),
                'utilization_percentage' => rand(58, 84) + (rand(0, 99) / 100),
                'license_number' => 'WHL-IBD-2024-001',
                'license_expiry' => Carbon::now()->addYears(1),
                'last_inspection_date' => Carbon::now()->subMonths(rand(1, 4)),
                'safety_rating' => 'B',
                'description' => 'Distribution center for Oyo State and surrounding areas.',
                'created_at' => Carbon::now()->subMonths(rand(6, 24)),
                'updated_at' => now(),
            ],

            // Enugu Warehouse
            [
                'warehouse_code' => 'WH-ENU-001',
                'name' => 'Enugu Eastern Hub',
                'type' => 'regional',
                'address' => '42 Ogui Road, Enugu',
                'city' => 'Enugu',
                'state' => 'Enugu',
                'country' => 'Nigeria',
                'postal_code' => '400102',
                'phone' => '+234-811-234-5009',
                'email' => 'enugu@warehouse.ng',
                'manager_name' => 'Chukwuemeka Eze',
                'manager_phone' => '+234-812-345-6009',
                'latitude' => 6.4403,
                'longitude' => 7.4994,
                'storage_capacity' => 2800,
                'current_occupancy' => rand(1400, 2500),
                'area_sqm' => 2000.00,
                'loading_docks' => 8,
                'staff_count' => 26,
                'opening_time' => '06:30:00',
                'closing_time' => '20:00:00',
                'operating_days' => json_encode(['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday']),
                'status' => 'active',
                'is_pickup_point' => true,
                'is_delivery_point' => true,
                'accepts_cod' => true,
                'has_cold_storage' => false,
                'has_24h_security' => true,
                'monthly_rent' => 700000.00,
                'utility_cost' => 135000.00,
                'total_shipments_processed' => rand(8000, 15000),
                'total_deliveries_completed' => rand(7000, 13000),
                'average_processing_time' => rand(3, 6) + (rand(0, 99) / 100),
                'utilization_percentage' => rand(59, 83) + (rand(0, 99) / 100),
                'license_number' => 'WHL-ENU-2023-001',
                'license_expiry' => Carbon::now()->addYears(2),
                'last_inspection_date' => Carbon::now()->subMonths(rand(1, 5)),
                'safety_rating' => 'B',
                'description' => 'Regional hub serving South-East Nigeria.',
                'created_at' => Carbon::now()->subMonths(rand(12, 36)),
                'updated_at' => now(),
            ],

            // Additional smaller facilities
            [
                'warehouse_code' => 'WH-LAG-004',
                'name' => 'Lekki Express Point',
                'type' => 'distribution',
                'address' => '89 Admiralty Way, Lekki Phase 1',
                'city' => 'Lagos',
                'state' => 'Lagos',
                'country' => 'Nigeria',
                'postal_code' => '105102',
                'phone' => '+234-813-234-5010',
                'email' => 'lekki@warehouse.ng',
                'manager_name' => 'Tunde Bakare',
                'manager_phone' => '+234-814-345-6010',
                'latitude' => 6.4474,
                'longitude' => 3.4701,
                'storage_capacity' => 1000,
                'current_occupancy' => rand(500, 900),
                'area_sqm' => 800.00,
                'loading_docks' => 4,
                'staff_count' => 12,
                'opening_time' => '08:00:00',
                'closing_time' => '18:00:00',
                'operating_days' => json_encode(['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday']),
                'status' => 'active',
                'is_pickup_point' => true,
                'is_delivery_point' => true,
                'accepts_cod' => true,
                'has_cold_storage' => false,
                'has_24h_security' => false,
                'monthly_rent' => 550000.00,
                'utility_cost' => 95000.00,
                'total_shipments_processed' => rand(3000, 7000),
                'total_deliveries_completed' => rand(2500, 6000),
                'average_processing_time' => rand(2, 4) + (rand(0, 99) / 100),
                'utilization_percentage' => rand(50, 75) + (rand(0, 99) / 100),
                'license_number' => 'WHL-LAG-2024-004',
                'license_expiry' => Carbon::now()->addMonths(18),
                'last_inspection_date' => Carbon::now()->subMonths(rand(1, 3)),
                'safety_rating' => 'C',
                'description' => 'Express pickup and delivery point for Lekki Peninsula.',
                'created_at' => Carbon::now()->subMonths(rand(3, 18)),
                'updated_at' => now(),
            ],
        ];
    }
}